repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.1
  hooks:
    # Run the linter.
    - id: ruff-check
      types_or: [python]
      args: [ --fix-only ]
    # Run the formatter.
    - id: ruff-format
      types_or: [python]